server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: first-service
        uri: http://127.0.0.1:18081/
        predicates:
          - Path=/first-service/**
        filters:
#          - AddRequestHeader=first-request, first-request-header2
#          - AddResponseHeader=first-response, first-response-header2
          - CustomFilter
      - id: second-service
        uri: http://127.0.0.1:18082/
        predicates:
          - Path=/second-service/**
        filters:
#          - AddRequestHeader=second-request, second-request-header2
#          - AddResponseHeader=second-response, second-response-header2
          - CustomFilter
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://127.0.0.1:9000/eureka/