server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: first-service
        uri: http://127.0.0.1:18081/
        predicates:
          - Path=/first-service/**
      - id: second-service
        uri: http://127.0.0.1:18082/
        predicates:
          - Path=/second-service/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://127.0.0.1:9000/eureka/