version: '3.9'
services:
  h2:
    build:
      context: ./h2
      dockerfile: Dockerfile
    container_name: h2_service
    ports:
      - "81:81"
      - "1521:1521"
    volumes:
      - ./docker/h2/data:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists