version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./local-rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf