server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ch01-spring-ai
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          no-store: true
          must-revalidate: true
  ai:
    openai:
      base-url: https://api.openai.com/v1
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo

logging:
  pattern:
    console: "%clr(%-5level) %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr(%logger{15}) : %msg%n"
