server:
  port: 8800

spring:
  application:
    name: discovery-service

eureka:
  client:
    registerWithEureka: false # ??? ???? ??? ???? ???.
    fetchRegistry: false      # ?? ???? ??? ???? ???.