server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:tcp://localhost:1521/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka

logging:
  level:
    org.hibernate.SQL: debug

greeting:
  message: Welcome to Simple E-Commerce User Service